annasoft/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [    
    path('', include('baseapp.urls')),
    path('crm/', include('crmapp.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace="authapp")),
    path('info/', include('knowledge_baseapp.urls')),
    path('fn/', include('FN_accounting.urls')),
    path('api/v1/', include('apiapp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()

apiapp/urls.py
from django.urls import path
from FN_accounting.views import (
    FNList,
    FNDetail,
    Point_of_saleList,
    KKTDetail,
    KKTFilterByPointOfSalesList
)

urlpatterns = [
    path('fn/kkt/list/<str:uid>/', KKTFilterByPointOfSalesList.as_view()),
    path('fn/', FNList.as_view()),
    path('fn/<str:uid>/', FNDetail.as_view()),
    path('fn/get-pos-list/<str:pk>/', Point_of_saleList.as_view()),
    path('fn/kkt/<str:uid>/', KKTDetail.as_view()),
]

authapp/urls.py
from django.urls import path

from authapp.views import (
    LoginView,
    LogoutView
)

app_name = 'authapp'

urlpatterns = [    
    path('', LoginView.as_view(), name='show-auth'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

authapp/forms.py
from django import forms
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Invisible

class UserForm(forms.Form):

	username = forms.CharField(max_length=191, required=True)	
	password = forms.CharField(max_length=40, required=True)


class ContactForm(forms.Form):
	
	firstName = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={
			'class': 'form-control',
			'placeholder': 'Имя *',
			'id': 'exampleInputName',
			'autocomplete': 'off',
			'onCopy':'return false',
			'onDrag': 'return false',
			'onDrop': 'return false',
			'onPaste': 'return false',
		}))
	phone = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={
			'class': 'form-control',
			'placeholder': 'Телефон *',
			'id': 'exampleInputPhone',
			'onKeyPress': 'inputFilter()',
			'autocomplete': 'off',
			'onCopy':'return false',
			'onDrag': 'return false',
			'onDrop': 'return false',
			'onPaste': 'return false',
		}))
	comment = forms.CharField(max_length=2048, required=True, widget=forms.Textarea(attrs={
			'class': 'form-control',
			'placeholder': 'Укажите тему обращения *',
			'id': 'exampleInputEnquiry-Description',
			'autocomplete': 'off',
		}))
	# accessData = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={
	# 		'class': 'custom-control-input',
	# 		'id': 'customCheck1',
	# 	}))
	captcha = ReCaptchaField(widget=ReCaptchaV2Invisible)

authapp/views.py
from django.shortcuts import (
	render,
	redirect
)
from django.contrib.auth import (
	authenticate,
	login,
	logout
)
from django.http import (
	HttpRequest,
	HttpResponse
)
from django.views.generic import View
from django.contrib import messages

from authapp.forms import UserForm

class LoginView(View):

	def get(self, request: HttpRequest) -> HttpResponse:
		return render(request, 'authapp/auth.html')
	
	def post(self, request: HttpRequest) -> HttpResponse:
		user_form = UserForm(request.POST)
		if user_form.is_valid():
			input_username = user_form.cleaned_data.get('username')
			input_password = user_form.cleaned_data.get('password')
			user = authenticate(
				request = request, 
				username = input_username, 
				password = input_password
			)
			if user is not None:
				login(request, user)
				return redirect('show-crm-index')
			else:
				messages.info(request, 'Комбинации пароль-логин не существует!')
				request.session['user_data'] = {
					'username': input_username,
					'password': input_password
				}	
		else:
			messages.info(request, 'Ошибка при вводе данных в форму!')		
		return redirect('authapp:show-auth')	


class LogoutView(View):

	def get(self, request: HttpRequest) -> HttpResponse:
		logout(request)
		return redirect('show-index')

authapp/templates/authapp/auth.html
{% extends 'baseapp/base.html' %}

{% load static %}

{% block content %}

{% if not user.is_authenticated %}
    <section class="space-ptb">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <div class="section-title text-center">                         
              <p>Введите логин и пароль</p>           
            </div>
          </div>
        </div>
        <div class="row justify-content-lg-around position-relative pt-5">
          <div class="col-lg-7 col-md-7 pr-lg-5">
            <div class="p-4 p-md-5 bg-white shadow">              
              <form class="mt-4" action="{% url 'authapp:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group mb-3">
                  {% if request.session.user_data %}
                  <input value="{{ request.session.user_data.username }} "type="text" class="form-control" name="username" placeholder="Имя пользователя" required>
                  {% else %}
                  <input type="text" class="form-control" name="username" placeholder="Имя пользователя" required>
                  {% endif %}
                </div>
                <div class="form-group mb-3">
                  {% if request.session.user_data %}
                  <input value="{{ request.session.user_data.password }}" type="password" class="form-control" name="password" placeholder="Пароль" required>
                  {% else %}
                  <input type="password" class="form-control" name="password" placeholder="Пароль" required>
                  {% endif %}
                </div>
                {% for message in messages %}
                  <p  style="color: red" class="text-uppercase" >* {{ message }} </p>
                {% endfor %}
                <div class="form-group mb-0">
                  <button type="submit" class="btn btn-primary">Войти<i class="fas fa-arrow-right pl-3"></i></button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
{% else %}
    <section class="space-ptb">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <div class="section-title text-center">                         
              <p>Для выхода нажмите Выйти</p>              
            </div>
          </div>
        </div>
        <div class="row justify-content-lg-around position-relative pt-5">
          <div class="col-lg-7 col-md-7 pr-lg-5">
            <div class="p-4 p-md-5 bg-white shadow">              
                <div class="form-group mb-3">
                  <input type="text" class="form-control" name="login" placeholder="login" value="{{ user }}" disabled>
                </div>
                <div class="form-group mb-0">
                  <a href="{% url 'authapp:logout' %}" class="btn btn-primary">Выйти<i class="fas fa-arrow-right pl-3"></i></a>
                </div>              
            </div>
          </div>
        </div>
      </div>
    </section>
{% endif %}

{% endblock %}